In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array((1, 2, 3))
print(a.shape)
print(a.size)
print(a)
print(b.shape)
print(b.size)

(3,)
3
[1 2 3]
(3,)
3


In [7]:
# 3d array example:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d)
print(arr3d.size)
print(arr3d.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
(2, 2, 3)


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]]]]]
number of dimensions : 5
