In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array((1, 2, 3))
print(a.shape)
print(a.size)
print(a)
print(b.shape)
print(b.size)

(3,)
3
[1 2 3]
(3,)
3


In [7]:
# 3d array example:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d)
print(arr3d.size)
print(arr3d.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
(2, 2, 3)
