In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array((1, 2, 3))
print(a.shape)
print(a.size)
print(a)
print(b.shape)
print(b.size)

(3,)
3
[1 2 3]
(3,)
3


In [7]:
# 3d array example:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d)
print(arr3d.size)
print(arr3d.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
(2, 2, 3)


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [23]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print("array shape : ", arr.shape)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
array shape :  (1, 1, 1, 1, 4)


In [13]:
arr = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print("Datatype of the array is : ", arr.dtype)
print("2nd element on the first row is : ", arr[0, 1])

Datatype of the array is :  int64
2nd element on the first row is :  2


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr2 = np.array(arr + a, dtype ='S')
print(arr2.dtype, "\n\n")
print(arr2)

|S21 


[[b'43' b'44' b'45' b'46' b'47']
 [b'48' b'49' b'50' b'51' b'52']]


In [21]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)
print(newarr.base) # if newarr is copy, base == None. else base is the original array.
# in this case the base is arr. hence newarr is just a copy.



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
arr = np.array([41, 42, 43, 44])
x = np.array([True, False, True, False])
print(arr[x])

[41 43]


In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a - b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[-3 -3 -3]


In [32]:
a = np.array([1, 2, 3])
b = np.array([4])
print(a + b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a - b)

[5 6 7]
[ 4  8 12]
[0.25 0.5  0.75]
[0 0 0]
[1 2 3]
[-3 -2 -1]


In [ ]:
# broadcasting works if that axis has the same shape or a 1
a = np.random.random((5, 6, 7, 1, 8, 3, 4 , 1))
b = np.random.random((5, 1, 7, 8, 8, 1, 4, 44))
print(a)
print(b)
print(a + b)